### ISSUE TITLE
Content::Pipeline::Filters::CodeHighlight is undefined 

### ISSUE THREAD

**Issue by tam-vo** [envygeeks/ruby-content-pipeline#6]
```
Content::Pipeline::Filters::CodeHighlight
NameError: uninitialized constant Content::Pipeline::Filters::CodeHighlight
```

Seems that the filter `Content::Pipeline::Filters::CodeHighlight` is not required in `filters.rb`, could you please check it again.

**Comment by envygeeks** [comment]
It is not a default filter at this time, are you asking for it to be a default filter?

**Comment by envygeeks** [comment]
This issue has remained unanswered for 30 days now so it is closing.
